name: 'Rsync Deployments Action'
description: 'GitHub Action for deploying code via rsync over ssh'
author: 'nbouaziz'
inputs:
  RSYNC_OPTIONS:
    description: 'The options of rsync'
    required: true
  SOURCE_FOLDER:
    description: 'The local path'
    required: true
  SSH_PRIVATE_KEY:
    description: 'Private SSH key allowed on server'
    required: true
  SSH_REMOTE_USER:
    description: 'User over SSH'
    required: true
  SSH_REMOTE_HOST:
    description: 'IP or domain of the host'
    required: true
  TARGET_FOLDER:
    description: 'Path on the host'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
